"""
LLM Analyzer – uses free Google Gemini API for market analysis.
"""

import logging
import os
from typing import Optional

logger = logging.getLogger(__name__)


def _ask_gemini(prompt: str, max_tokens: int = 512) -> Optional[str]:
    """Send a prompt to Gemini and return the text response."""
    api_key = os.getenv("GEMINI_API_KEY", "")
    if not api_key:
        return None
    try:
        from google import genai
        client   = genai.Client(api_key=api_key)
        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt,
        )
        return response.text.strip()
    except ImportError:
        try:
            import google.generativeai as genai_legacy
            genai_legacy.configure(api_key=api_key)
            model    = genai_legacy.GenerativeModel("gemini-1.5-flash")
            response = model.generate_content(prompt)
            return response.text.strip()
        except Exception as exc:
            logger.warning(f"Gemini legacy fallback failed: {exc}")
            return None
    except Exception as exc:
        logger.warning(f"Gemini request failed: {exc}")
        return None


# ──────────────────────────────────────────────────────────
# PUBLIC FUNCTIONS
# ──────────────────────────────────────────────────────────

def generate_market_summary(signals: list[dict]) -> str:
    """
    Summarise current trading signals and market conditions.

    Args:
        signals: List of signal dicts (symbol, signal, confidence, strategy, price)

    Returns:
        Human-readable market summary string.
    """
    if not signals:
        return "No signals available."

    lines = [f"- {s['symbol']}: {s['signal']} ({s['strategy']}, conf={s['confidence']:.2f})" for s in signals]
    signal_text = "\n".join(lines)

    prompt = (
        "You are a quantitative analyst. Given the following algorithmic trading signals, "
        "provide a concise 3-4 sentence market summary covering overall bias (bullish/bearish/mixed), "
        "key opportunities, and any notable risks. Be factual and data-driven.\n\n"
        f"Signals:\n{signal_text}"
    )

    result = _ask_gemini(prompt)
    if result:
        return result
    # Fallback: simple summary
    buys  = sum(1 for s in signals if s.get("signal") == "BUY")
    sells = sum(1 for s in signals if s.get("signal") == "SELL")
    holds = len(signals) - buys - sells
    return (
        f"Market Summary: {buys} BUY, {sells} SELL, {holds} HOLD signals across "
        f"{len(signals)} assets. (Gemini unavailable – falling back to basic summary.)"
    )


def analyze_strategy_performance(metrics: dict) -> str:
    """
    Get LLM-generated improvement suggestions for strategy metrics.

    Args:
        metrics: Dict of backtest metrics (win_rate, sharpe, max_drawdown, etc.)

    Returns:
        Suggestions as a string.
    """
    prompt = (
        "You are an expert quantitative researcher. Analyse these backtest metrics and "
        "provide 3-5 actionable improvement suggestions (focus on risk-adjusted returns):\n\n"
        f"{metrics}"
    )
    result = _ask_gemini(prompt, max_tokens=600)
    return result or "LLM analysis unavailable. Review metrics manually."


def get_trade_reasoning(signal: dict) -> str:
    """
    Explain why a specific signal was generated.

    Args:
        signal: Signal dict with symbol, signal, strategy, confidence, and details.

    Returns:
        Plain-English explanation.
    """
    prompt = (
        "You are a trading systems analyst. Explain in 2-3 sentences why the following "
        "algorithmic trading signal was generated. Be specific about the indicator values.\n\n"
        f"Signal: {signal}"
    )
    result = _ask_gemini(prompt, max_tokens=300)
    return result or (
        f"{signal.get('signal', 'HOLD')} signal for {signal.get('symbol', '?')} "
        f"generated by {signal.get('strategy', '?')} strategy with "
        f"{signal.get('confidence', 0):.2f} confidence."
    )
